# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QStackedWidget, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(800, 600)
        self.stackedWidget = QStackedWidget(Widget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(30, 210, 731, 261))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.VmNamelabel = QLabel(self.page)
        self.VmNamelabel.setObjectName(u"VmNamelabel")
        self.VmNamelabel.setGeometry(QRect(10, 60, 121, 16))
        self.RemoteFsLlabel = QLabel(self.page)
        self.RemoteFsLlabel.setObjectName(u"RemoteFsLlabel")
        self.RemoteFsLlabel.setGeometry(QRect(380, 150, 121, 16))
        self.HostnameIpLabel = QLabel(self.page)
        self.HostnameIpLabel.setObjectName(u"HostnameIpLabel")
        self.HostnameIpLabel.setGeometry(QRect(10, 90, 121, 16))
        self.JenkinsCredsLabel = QLabel(self.page)
        self.JenkinsCredsLabel.setObjectName(u"JenkinsCredsLabel")
        self.JenkinsCredsLabel.setGeometry(QRect(380, 60, 141, 16))
        self.LabelsLabel = QLabel(self.page)
        self.LabelsLabel.setObjectName(u"LabelsLabel")
        self.LabelsLabel.setGeometry(QRect(10, 120, 121, 16))
        self.ExecutorsLabel = QLabel(self.page)
        self.ExecutorsLabel.setObjectName(u"ExecutorsLabel")
        self.ExecutorsLabel.setGeometry(QRect(10, 150, 121, 16))
        self.PortLabel = QLabel(self.page)
        self.PortLabel.setObjectName(u"PortLabel")
        self.PortLabel.setGeometry(QRect(380, 90, 141, 16))
        self.DescriptionLabel = QLabel(self.page)
        self.DescriptionLabel.setObjectName(u"DescriptionLabel")
        self.DescriptionLabel.setGeometry(QRect(380, 120, 141, 16))
        self.VmNameLineEdit = QLineEdit(self.page)
        self.VmNameLineEdit.setObjectName(u"VmNameLineEdit")
        self.VmNameLineEdit.setGeometry(QRect(152, 60, 131, 20))
        self.HostnameOrIpLineEdit = QLineEdit(self.page)
        self.HostnameOrIpLineEdit.setObjectName(u"HostnameOrIpLineEdit")
        self.HostnameOrIpLineEdit.setGeometry(QRect(152, 90, 131, 20))
        self.LabelsLineEdit = QLineEdit(self.page)
        self.LabelsLineEdit.setObjectName(u"LabelsLineEdit")
        self.LabelsLineEdit.setGeometry(QRect(152, 120, 131, 20))
        self.ExecutorsLineEdit = QLineEdit(self.page)
        self.ExecutorsLineEdit.setObjectName(u"ExecutorsLineEdit")
        self.ExecutorsLineEdit.setGeometry(QRect(152, 150, 131, 20))
        self.JenkinsCredsIdLineEdit = QLineEdit(self.page)
        self.JenkinsCredsIdLineEdit.setObjectName(u"JenkinsCredsIdLineEdit")
        self.JenkinsCredsIdLineEdit.setGeometry(QRect(550, 60, 171, 16))
        self.PortLlineEdit = QLineEdit(self.page)
        self.PortLlineEdit.setObjectName(u"PortLlineEdit")
        self.PortLlineEdit.setGeometry(QRect(550, 90, 171, 16))
        self.DescriptionLineEdit = QLineEdit(self.page)
        self.DescriptionLineEdit.setObjectName(u"DescriptionLineEdit")
        self.DescriptionLineEdit.setGeometry(QRect(550, 120, 171, 16))
        self.RemoteFsLineEdit = QLineEdit(self.page)
        self.RemoteFsLineEdit.setObjectName(u"RemoteFsLineEdit")
        self.RemoteFsLineEdit.setGeometry(QRect(550, 150, 171, 16))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.JenkinsCredsIdLineEdit_2 = QLineEdit(self.page_2)
        self.JenkinsCredsIdLineEdit_2.setObjectName(u"JenkinsCredsIdLineEdit_2")
        self.JenkinsCredsIdLineEdit_2.setGeometry(QRect(490, 60, 231, 20))
        self.RemoteFsLlabel_2 = QLabel(self.page_2)
        self.RemoteFsLlabel_2.setObjectName(u"RemoteFsLlabel_2")
        self.RemoteFsLlabel_2.setGeometry(QRect(350, 150, 121, 16))
        self.VmNameLineEdit_2 = QLineEdit(self.page_2)
        self.VmNameLineEdit_2.setObjectName(u"VmNameLineEdit_2")
        self.VmNameLineEdit_2.setGeometry(QRect(152, 60, 171, 20))
        self.JenkinsCredsLabel_2 = QLabel(self.page_2)
        self.JenkinsCredsLabel_2.setObjectName(u"JenkinsCredsLabel_2")
        self.JenkinsCredsLabel_2.setGeometry(QRect(350, 60, 121, 16))
        self.HostnameIpLabel_2 = QLabel(self.page_2)
        self.HostnameIpLabel_2.setObjectName(u"HostnameIpLabel_2")
        self.HostnameIpLabel_2.setGeometry(QRect(10, 90, 91, 16))
        self.LabelsLineEdit_2 = QLineEdit(self.page_2)
        self.LabelsLineEdit_2.setObjectName(u"LabelsLineEdit_2")
        self.LabelsLineEdit_2.setGeometry(QRect(152, 120, 171, 20))
        self.HostnameOrIpLineEdit_2 = QLineEdit(self.page_2)
        self.HostnameOrIpLineEdit_2.setObjectName(u"HostnameOrIpLineEdit_2")
        self.HostnameOrIpLineEdit_2.setGeometry(QRect(152, 90, 171, 20))
        self.DescriptionLabel_2 = QLabel(self.page_2)
        self.DescriptionLabel_2.setObjectName(u"DescriptionLabel_2")
        self.DescriptionLabel_2.setGeometry(QRect(350, 120, 121, 16))
        self.VmNamelabel_2 = QLabel(self.page_2)
        self.VmNamelabel_2.setObjectName(u"VmNamelabel_2")
        self.VmNamelabel_2.setGeometry(QRect(10, 60, 91, 16))
        self.LabelsLabel_2 = QLabel(self.page_2)
        self.LabelsLabel_2.setObjectName(u"LabelsLabel_2")
        self.LabelsLabel_2.setGeometry(QRect(10, 120, 91, 16))
        self.ExecutorsLabel_2 = QLabel(self.page_2)
        self.ExecutorsLabel_2.setObjectName(u"ExecutorsLabel_2")
        self.ExecutorsLabel_2.setGeometry(QRect(10, 150, 91, 16))
        self.ExecutorsLineEdit_2 = QLineEdit(self.page_2)
        self.ExecutorsLineEdit_2.setObjectName(u"ExecutorsLineEdit_2")
        self.ExecutorsLineEdit_2.setGeometry(QRect(152, 150, 171, 20))
        self.RemoteFsLineEdit_2 = QLineEdit(self.page_2)
        self.RemoteFsLineEdit_2.setObjectName(u"RemoteFsLineEdit_2")
        self.RemoteFsLineEdit_2.setGeometry(QRect(490, 150, 231, 20))
        self.DescriptionLineEdit_2 = QLineEdit(self.page_2)
        self.DescriptionLineEdit_2.setObjectName(u"DescriptionLineEdit_2")
        self.DescriptionLineEdit_2.setGeometry(QRect(490, 120, 231, 20))
        self.stackedWidget.addWidget(self.page_2)
        self.UrlLineEdit = QLineEdit(Widget)
        self.UrlLineEdit.setObjectName(u"UrlLineEdit")
        self.UrlLineEdit.setGeometry(QRect(172, 50, 221, 21))
        self.UsernameLineEdit = QLineEdit(Widget)
        self.UsernameLineEdit.setObjectName(u"UsernameLineEdit")
        self.UsernameLineEdit.setGeometry(QRect(172, 90, 221, 21))
        self.tokenLineEdit = QLineEdit(Widget)
        self.tokenLineEdit.setObjectName(u"tokenLineEdit")
        self.tokenLineEdit.setGeometry(QRect(172, 130, 221, 21))
        self.UrlLabel = QLabel(Widget)
        self.UrlLabel.setObjectName(u"UrlLabel")
        self.UrlLabel.setGeometry(QRect(40, 50, 111, 20))
        self.UsernameLabel = QLabel(Widget)
        self.UsernameLabel.setObjectName(u"UsernameLabel")
        self.UsernameLabel.setGeometry(QRect(40, 90, 111, 20))
        self.tokenLabel = QLabel(Widget)
        self.tokenLabel.setObjectName(u"tokenLabel")
        self.tokenLabel.setGeometry(QRect(40, 130, 111, 16))
        self.RunPushButton = QPushButton(Widget)
        self.RunPushButton.setObjectName(u"RunPushButton")
        self.RunPushButton.setGeometry(QRect(660, 520, 111, 32))
        self.QuitPushButton = QPushButton(Widget)
        self.QuitPushButton.setObjectName(u"QuitPushButton")
        self.QuitPushButton.setGeometry(QRect(520, 520, 100, 32))
        self.MethodLabel = QLabel(Widget)
        self.MethodLabel.setObjectName(u"MethodLabel")
        self.MethodLabel.setGeometry(QRect(400, 170, 121, 16))
        self.MethodComboBox = QComboBox(Widget)
        self.MethodComboBox.addItem("")
        self.MethodComboBox.addItem("")
        self.MethodComboBox.setObjectName(u"MethodComboBox")
        self.MethodComboBox.setGeometry(QRect(530, 170, 111, 32))
        self.ActionComboBox = QComboBox(Widget)
        self.ActionComboBox.addItem("")
        self.ActionComboBox.addItem("")
        self.ActionComboBox.addItem("")
        self.ActionComboBox.addItem("")
        self.ActionComboBox.addItem("")
        self.ActionComboBox.addItem("")
        self.ActionComboBox.addItem("")
        self.ActionComboBox.addItem("")
        self.ActionComboBox.addItem("")
        self.ActionComboBox.addItem("")
        self.ActionComboBox.setObjectName(u"ActionComboBox")
        self.ActionComboBox.setGeometry(QRect(190, 170, 103, 32))
        self.ActionLabel = QLabel(Widget)
        self.ActionLabel.setObjectName(u"ActionLabel")
        self.ActionLabel.setGeometry(QRect(40, 170, 58, 16))

        self.retranslateUi(Widget)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.VmNamelabel.setText(QCoreApplication.translate("Widget", u"VM Name", None))
        self.RemoteFsLlabel.setText(QCoreApplication.translate("Widget", u"Remote Filesystem", None))
        self.HostnameIpLabel.setText(QCoreApplication.translate("Widget", u"Hostname/IP", None))
        self.JenkinsCredsLabel.setText(QCoreApplication.translate("Widget", u"Jenkins Credentials ID", None))
        self.LabelsLabel.setText(QCoreApplication.translate("Widget", u"Labels", None))
        self.ExecutorsLabel.setText(QCoreApplication.translate("Widget", u"Executors", None))
        self.PortLabel.setText(QCoreApplication.translate("Widget", u"Port", None))
        self.DescriptionLabel.setText(QCoreApplication.translate("Widget", u"Description", None))
        self.PortLlineEdit.setText(QCoreApplication.translate("Widget", u"22", None))
        self.RemoteFsLlabel_2.setText(QCoreApplication.translate("Widget", u"Remote Filesystem", None))
        self.JenkinsCredsLabel_2.setText(QCoreApplication.translate("Widget", u"JVM Options", None))
        self.HostnameIpLabel_2.setText(QCoreApplication.translate("Widget", u"Hostname/IP", None))
        self.DescriptionLabel_2.setText(QCoreApplication.translate("Widget", u"Description", None))
        self.VmNamelabel_2.setText(QCoreApplication.translate("Widget", u"VM Name", None))
        self.LabelsLabel_2.setText(QCoreApplication.translate("Widget", u"Labels", None))
        self.ExecutorsLabel_2.setText(QCoreApplication.translate("Widget", u"Executors", None))
        self.UrlLabel.setText(QCoreApplication.translate("Widget", u"URL", None))
        self.UsernameLabel.setText(QCoreApplication.translate("Widget", u"username", None))
        self.tokenLabel.setText(QCoreApplication.translate("Widget", u"token/password", None))
        self.RunPushButton.setText(QCoreApplication.translate("Widget", u"run command", None))
        self.QuitPushButton.setText(QCoreApplication.translate("Widget", u"quit", None))
        self.MethodLabel.setText(QCoreApplication.translate("Widget", u"Method", None))
        self.MethodComboBox.setItemText(0, QCoreApplication.translate("Widget", u"SSH", None))
        self.MethodComboBox.setItemText(1, QCoreApplication.translate("Widget", u"JNLP", None))

        self.ActionComboBox.setItemText(0, QCoreApplication.translate("Widget", u"Add", None))
        self.ActionComboBox.setItemText(1, QCoreApplication.translate("Widget", u"Update", None))
        self.ActionComboBox.setItemText(2, QCoreApplication.translate("Widget", u"Get Nodes", None))
        self.ActionComboBox.setItemText(3, QCoreApplication.translate("Widget", u"Get Node Info", None))
        self.ActionComboBox.setItemText(4, QCoreApplication.translate("Widget", u"Get Node Config", None))
        self.ActionComboBox.setItemText(5, QCoreApplication.translate("Widget", u"Node Exists", None))
        self.ActionComboBox.setItemText(6, QCoreApplication.translate("Widget", u"New Item", None))
        self.ActionComboBox.setItemText(7, QCoreApplication.translate("Widget", u"Delete", None))
        self.ActionComboBox.setItemText(8, QCoreApplication.translate("Widget", u"Disable", None))
        self.ActionComboBox.setItemText(9, QCoreApplication.translate("Widget", u"Enable", None))

        self.ActionLabel.setText(QCoreApplication.translate("Widget", u"Action", None))
    # retranslateUi

