pipeline {
    agent none 
    stages {
        stage('pre-parallel') {
            steps{
                echo 'Running pre-parallel stage'
            }
        }
        stage('Parallel build Pipelines') {
            parallel {
                stage('macOS Pipeline') {
                    agent { label 'macos' }
                    stages {
                        stage('macOS Build') { 
                            steps {
                                dir('src/BuildScripts') {
                                    sh './build.macos.sh' 
                                }
                            }
                        }
                    }
                }
                stage('Rocky 10 Pipeline') {
                    agent { label 'rocky10' }
                    stages {
                        stage('rocky10 Build') { 
                            steps {
                                dir('src/BuildScripts') {
                                    sh './build.rh-based.sh' 
                                } 
                            }
                        }
                    }
                }
                stage('Debian Pipeline') {
                    agent { label 'debian' }
                    stages {
                        stage('debian Build') { 
                            steps {
                                dir('src/BuildScripts') {
                                    sh './build.deb-based.sh' 
                                } 
                            }
                        }
                    }
                }
                stage('Windows Pipeline') {
                    agent { label 'windows' }
                    stages {
                        stage('Windows Build') { 
                            steps {
                                dir('src/BuildScripts') {
                                    powershell './build.windows.ps1' 
                                } 
                            }
                        }
                    }
                }
            }
        }
        stage('Parallel test pipelines') {
            parallel {
                stage('macOS Pipeline') {
                    agent { label 'macos' }
                    environment {
                        VENV = "../../projEnv"
                        QT_QPA_PLATFORM = "offscreen"
                    }
                    stages {
                        stage('macOS Test') { 
                            steps {
                                dir('src/jenkinsTools/tests') {
                                    echo '----------=====### Starting Tests ###=====----------'
                                    sh """
                                        ls -l
                                        . ${VENV}/bin/activate
                                        ${VENV}/bin/python -m pytest -v --junit-xml test-reports/results.xml
                                    """
                                    echo '----------=====### Finished Tests ###=====----------'
                                    junit 'test-reports/results.xml'
                                }
                            }
                        }
                    }
                }
                stage('Rocky 10 Pipeline') {
                    agent { label 'rocky10' }
                    environment {
                        VENV = "../../projEnv"
                        QT_QPA_PLATFORM = "offscreen"
                    }
                    stages {
                        stage('Rocky10 Test') { 
                            steps {
                                dir('src/jenkinsTools/tests') {
                                    echo '----------=====### Starting Tests ###=====----------'
                                    sh """
                                        ls -l
                                        . ${VENV}/bin/activate
                                        ${VENV}/bin/python -m pytest -v --junit-xml test-reports/results.xml
                                    """
                                    echo '----------=====### Finished Tests ###=====----------'
                                    junit 'test-reports/results.xml'
                                }
                            }
                        }
                    }
                }
                stage('Debian Pipeline') {
                    agent { label 'debian' }
                    environment {
                        VENV = "../../projEnv"
                        QT_QPA_PLATFORM = "offscreen"
                    }
                    stages {
                        stage('Debian Test') { 
                            steps {
                                dir('src/jenkinsTools/tests') {
                                    echo '----------=====### Starting Tests ###=====----------'
                                    sh """
                                        ls -l
                                        . ${VENV}/bin/activate
                                        ${VENV}/bin/python -m pytest -v --junit-xml test-reports/results.xml
                                    """
                                    echo '----------=====### Finished Tests ###=====----------'
                                    junit 'test-reports/results.xml'
                                }
                            }
                        }
                    }
                }
                stage('Windows Pipeline') {
                    agent { label 'windows' }
                    environment {
                        VENV = "../../projEnv"
                    }
                    stages {
                        stage('Windows Test') { 
                            steps {
                                dir('src/jenkinsTools/tests') {
                                    echo '----------=====### Starting Tests ###=====----------'
                                    powershell """
                                        ls -l
                                        ${VENV}/Scripts/Activate.ps1
                                        ${VENV}/bin/python -m pytest -v --junit-xml test-reports/results.xml
                                    """
                                    echo '----------=====### Finished Tests ###=====----------'
                                    junit 'test-reports/results.xml'
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('post-parallel') {
            steps {
                echo 'Running post-parallel stage'
            }
        }
    }
}
